language: ruby
rvm:
  - 2.6.2
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
addons:
  postgresql: '11.4'
env:
  - DATABASE_URL=postgresql://postgres@localhost/travis_ci_test
