# These keys from from the source of BodegaBot
# https://cheapbotsdonequick.com/source/BodegaBot
# "employees": ["employees","founders","designers","programmers","engineers","product managers","interns"],
#
# NOTE: If you're adding somebody other than yourself, make sure you have their permission!
#
"employees":
  - bfezga
  - chiangku
  - crabbylions
  - cytochrome
  - jeeyoungk
  - sentiental
  - tuanycakes
  - vslavich
  - abhay
"founders":
"designers":
  - vslavich
"programmers":
  - chiangku
  - cytochrome
  - jeeyoungk
  - sentiental
  - abhay
"engineers":
  - chiangku
  - cytochrome
  - jeeyoungk
  - sentiental
  - tuanycakes
  - abhay
"product managers":
  - bfezga
  - crabbylions
  - vslavich
"interns":
